### ISSUE TITLE
LaunchDaemon RunAtLoad

### ISSUE THREAD

**Issue by kevinmcox** [jelockwood/pinpoint#14]
John, what would you think about adding the `RunAtLoad` key to the LaunchDaemon so it triggers a location check right when the computer boots up?

I'd be happy to add it to my existing PR #13 if you are OK with it.

~ Kevin

**Comment by jelockwood** [comment]
@kevinmcox
Yes that sounds a good idea.

**Comment by kevinmcox** [comment]
Thanks, I committed it to #13 .
