### ISSUE TITLE
Errors in LaunchDaemon

### ISSUE THREAD

**Issue by jelockwood** [jelockwood/pinpoint#2]
The original launchdaemon plist forgot to specify the binary was a .sh script. It also had the startinterval wrong at 10 minutes instead of 60 minutes i.e. one hour.

**Comment by jelockwood** [comment]
Corrected file path in launchdaemon plist.
Corrected startinterval to 3600 seconds i.e. hourly.

**Comment by myoaungchit** [comment]
Hi there, I deployed the pinpoint via jamf and using your jss extension to read the location data in the com.jelockwood.pinpoint.plist. Base on the plist setting , the location data should be regenerated every hour but I noticed that it is not doing it. Is there any command I can add in jss extension script to force regenerate the location data in plist before reading it ? Thank you.

**Comment by jelockwood** [comment]
The way you are using it there are two parts involved. There is the main part which is a combination of a shell script and launchdaemon that gets installed on the client Mac, and a script that gets run via JSS to query the results from the client Mac and store as a extension attribute in JSS.

Have you installed the client portion? If so have a look at the results file directly.

And yes, it would be possible to have the JSS extension attribute script force a regeneration by adding a line at the beginning to first run the main pinpoint.sh script as follows.

/Library/Application\ Support/pinpoint/bin/pinpoint.sh

Let me know your results so I can close this issue or take further action.

**Comment by myoaungchit** [comment]
Thank you for checking on this very fast. Yes, I did the installation for client portion prior to adding JSS extension.

 So , in JSS extension, `/Library/Application\ Support/pinpoint/bin/pinpoint.sh` is added to force generated the location data. However, the new location data was not reflecting in plist after JAMF Inventory Update. I noticed that the time stamp for LastLocationRun was not same as LastRun. For LastRun's timestamp, it tallied with the time stamp for JAMF Inventory Update. 

<img width="682" alt="screenshot_2019-02-25_at_8_39_42_am" src="https://user-images.githubusercontent.com/2579082/53324545-fd6a1980-391b-11e9-8246-28a2e97bf7a2.png">

I changed the command to `/Library/Application\ Support/pinpoint/bin/pinpoint.sh -g` to see how it goes and , to my surprise, it did update the new location data in plist now.

<img width="300" alt="screenshot 2019-02-25 at 4 49 45 pm" src="https://user-images.githubusercontent.com/2579082/53325070-63a36c00-391d-11e9-8935-37ba1da436dc.png">

This was tested on the laptops which are currently away from Singapore and their new locations are reflected correctly. 

Really appreciate for your work and help, John.

**Comment by jelockwood** [comment]
If it works with -g aka --geocode but not without then it might be related to this now fixed bug https://github.com/jelockwood/pinpoint/issues/4#issuecomment-465594032 that is the installer was originally not correctly setting the default value of the USE_GEOCODE preference to TRUE.

If you run the 3.0.3 installer it should in theory set this to TRUE even for existing installs but check it afterwards by doing

defaults read /Library/Preferences/com.jelockwood.pinpoint

Can you check what version of pinpoint you have installed, the current version is now 3.0.3. The version number is in the installer package but also in the pinpoint.sh script, you can also do

`/Library/Application\ Support/pinpoint/bin/pinpoint.sh -V`

**Comment by jelockwood** [comment]
Transferred to new issue and reclosed original one.
