### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by ofirgalcon** [jelockwood/pinpoint#3]
iMac with 10.13.6, had pinpoint v2 installed

Feb 19 03:56:04 Thin Installer[76682]: @(#)PROGRAM:Install  PROJECT:Install-1000
Feb 19 03:56:04 Thin Installer[76682]: @(#)PROGRAM:Installer  PROJECT:Installer-920
Feb 19 03:56:04 Thin Installer[76682]: Hardware: iMac14,2 @ 3.20 GHz (x 4), 16384 MB RAM
Feb 19 03:56:04 Thin Installer[76682]: Running OS Build: Mac OS X 10.13.6 (17G6009)
Feb 19 03:56:04 Thin Installer[76682]: pinpoint  Installation Log
Feb 19 03:56:04 Thin Installer[76682]: Opened from: /Users/ofir/Downloads/pinpoint-3.0.1.pkg
Feb 19 03:56:06 Thin deleted[969]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=78051=0x130e3 expectedThread=10759=0x2a07
Feb 19 03:56:11 Thin deleted[969]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=52771=0xce23 expectedThread=10759=0x2a07
Feb 19 03:56:11 Thin Installer[76682]: InstallerStatusNotifications plugin loaded
Feb 19 03:56:15 Thin Installer[76682]: ================================================================================
Feb 19 03:56:15 Thin Installer[76682]: User picked Standard Install
Feb 19 03:56:15 Thin Installer[76682]: Choices selected for installation:
Feb 19 03:56:15 Thin Installer[76682]: 	Upgrade: "pinpoint"
Feb 19 03:56:15 Thin Installer[76682]: 	Upgrade: "pinpoint"
Feb 19 03:56:15 Thin Installer[76682]: ================================================================================
Feb 19 03:56:15 Thin deleted[969]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=78051=0x130e3 expectedThread=10759=0x2a07
Feb 19 03:56:16 Thin Installer[76682]: Configuring volume "Macintosh HD"
Feb 19 03:56:16 Thin Installer[76682]: Free space on "Macintosh HD": 197.94 GB (197937045504 bytes).
Feb 19 03:56:16 Thin Installer[76682]: Create temporary directory "/var/folders/39/n4jn4q556ln07yd5v531rr_h0000gx/T//Install.76682zEu3mU"
Feb 19 03:56:16 Thin Installer[76682]: IFPKInstallElement (1 packages)
Feb 19 03:56:16 Thin Installer[76682]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Feb 19 03:56:16 Thin installd[14937]: PackageKit: ----- Begin install -----
Feb 19 03:56:16 Thin installd[14937]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “pinpoint-3.0.1.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/ofir/Downloads/pinpoint-3.0.1.pkg#pinpoint.pkg, PKInstallPackageIdentifier=com.jelockwood.pinpoint.pkg., NSLocalizedDescription=An error occurred while running scripts from the package “pinpoint-3.0.1.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cpinpoint-3.0.1.pkg\U201d.";
	    NSURL = "file://localhost/Users/ofir/Downloads/pinpoint-3.0.1.pkg#pinpoint.pkg";
	    PKInstallPackageIdentifier = "com.jelockwood.pinpoint.pkg.";
	}
Feb 19 03:56:17 Thin Installer[76682]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Feb 19 03:56:17 Thin Installer[76682]: IFDInstallController 1C00 state = 8
Feb 19 03:56:17 Thin Installer[76682]: Displaying 'Install Failed' UI.
Feb 19 03:56:17 Thin Installer[76682]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

**Comment by jelockwood** [comment]
I have managed to reproduce the error so I will look in to this for you.

**Comment by jelockwood** [comment]
@ofirgalcon 
Ok, it turns out there was zero errors in my code and even in my pre and post install scripts. 👍 

All I had to do was recreate the installer package using a newer version of the Packages tool to make it High Sierra compatible. Please download the new 3.0.2 release and confirm this also solves the problem for you and I can then close this issue.

**Comment by ofirgalcon** [comment]
I somehow lost track of the installer link...

**Comment by jelockwood** [comment]
It is on the releases page here - https://github.com/jelockwood/pinpoint/releases

**Comment by ofirgalcon** [comment]
Obviously... Thanks. I got it installed - it works, but it isn't reported the address, just the coordinates. I pushed it out to some test clients so I will know more later.

**Comment by jelockwood** [comment]
Have you registered for a Google API key as per my Wiki page here? - https://github.com/jelockwood/pinpoint/wiki/Google-APIs

You then need to add the API key to each client Mac as per - https://github.com/jelockwood/pinpoint/wiki/Preferences

**Comment by ofirgalcon** [comment]
Yes I have - it's working ok, returning co-ordinates, but a blank address.

sudo defaults write /Library/Preferences/com.jelockwood.pinpoint.plist YOUR_API_KEY xxxxxx
sudo defaults write /Library/Preferences/com.jelockwood.pinpoint.plist USE_ALTITUDE -bool FALSE
sudo defaults write /Library/Preferences/com.jelockwood.pinpoint.plist USE_GEOCODE -bool TRUE

**Comment by ofirgalcon** [comment]
/Library/Application\ Support/pinpoint/bin/pinpoint.sh
HTTP/2 200 
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: Mon, 01 Jan 1990 00:00:00 GMT
date: Wed, 20 Feb 2019 09:19:34 GMT
vary: X-Origin
vary: Origin,Accept-Encoding
content-type: application/json; charset=UTF-8
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
server: GSE
alt-svc: quic=":443"; ma=2592000; v="44,43,39"
accept-ranges: none

{
 "location": {
  "lat": xx.xxxxx,
  "lng": xx.xxxxx
 },
 "accuracy": 27.0
}
Result code = 200
ls_enabled = 1
-----------
This is what gets returned

sudo defaults read "/Library/Application Support/pinpoint/location.plist"
{
    Address = "";
    Altitude = 0;
    CurrentStatus = Successful;
    GoogleMap = "https://www.google.com/maps/place/xxxxxxxxxxx";
    "LS_Enabled" = 0;
    LastLocationRun = "2019-02-20 09:11:35 +0000";
    LastRun = "2019-02-20 09:11:35 +0000";
    Latitude = "xx.xxxxx";
    LatitudeAccuracy = 23;
    Longitude = "xx.xxxxxx";
    LongitudeAccuracy = 23;
    StaleLocation = No;

**Comment by jelockwood** [comment]
I am closing this issue and I have opened a new one for the new issue. See it here - 
https://github.com/jelockwood/pinpoint/issues/4
