### ISSUE TITLE
Missing 'fi' in if statement in 3.0.4

### ISSUE THREAD

**Issue by sswany** [jelockwood/pinpoint#8]
I was trying to install the current 3.0.4 pkg and realized the postinstall script was failing from what looks like a missing 'fi' in the if statement? I was able to update the postinstall manually and seems to fix it.

Thanks!

**Comment by kevinmcox** [comment]
I can confirm, the `postinstall` in the package doesn't match here: https://github.com/jelockwood/pinpoint/blob/master/installer_package/postinstall.sh

**Comment by jelockwood** [comment]
@sswany @kevinmcox 
When I built v3.0.4 it was using a copy from an old laptop moved to a new laptop. Somehow the postinstall.sh file ended up being incomplete. I will create a new release with this remedied.

Done now posted. Can you check this one both has a working postintall script and still has the correct code.

**Comment by sswany** [comment]
Looks like its working now. Thanks!

**Comment by kevinmcox** [comment]
Looks good!
